### ISSUE TITLE
Problems with GPS-Logger 3

### ISSUE THREAD

**Issue by neffets88** [davidmcq137/JetiLuaDFM#20]
Hi David,
Thanks for sharing your work with us! Today I tried to use the GPS-Maps app on my ds24 in order to fly some triangles...
The App works great so far but does not show the right Speed values from my GPS-Logger (sm-Modellbau). It calls out the right "alt" value but the "speed" is always zero. It's not possible to start the Race. The position of the glider is also shown right.
Let me know if you need any logs or something for debugging. It's of course also possible that I did something wrong 😉
Greetings
Steffen

**Comment by davidmcq137** [comment]
thanks for reaching out here. please email me at ww2birds@optonline.net so we can get in touch directly .. I have some questions  about the telemetry config that may help us get it going quickly. I have also ordered one (I did not know about that device, it looks very nice!) so for sure we will get this straightened out promptly.

I also tried to contact you via FB messenger... so sorry if this is a duplicate.

Dave

**Comment by davidmcq137** [comment]
here is the email I tried to reply with:

Hi Steffen,

Thanks for the email.

Happy to help you sort it out. And, I can support the sm-Modellbau sensor in my config file with some additional information. But .. it should work correctly even if you assign it manually. As a start, can you send me pictures or screenshots of the Sensors/Logging setup screens that shows all the sm-Modellbau sensors along with their slot numbers and units. It is possible if it is using unknown (to me) units then it is set to zero. This will be a big help to sort it out, and will also let me put that sensor into my GPS config file so it will be assigned automatically on startup.

Also please send me a screenshot of the DFM-Maps app's Telemetry sensors menu.

Next, if you put a single window on the TX screen for speed does it show up correctly (just the standard telemetry display)?

Let's start with this and I know we can get it sorted out quickly.

Dave

**Comment by neffets88** [comment]
Hi David,

here are the pictures from the display of my DC-24. I used some pre-release Versions of the App for testing also. With the “normal” release there were less options...

Also I am sending you the log file of one of my flights. I hope that helps. I can take more pictures later, if you need something else.

I hope that helps!

**Comment by davidmcq137** [comment]
Replied to you directly .. should be all set but please let me know.

**Comment by davidmcq137** [comment]
Steffen confirms it's working. Closing.
