### ISSUE TITLE
DFM-TriM

### ISSUE THREAD

**Issue by pavelhkcz** [davidmcq137/JetiLuaDFM#6]
Hello,

I'm starting to fly GPS triangle racing and I tried the script DFM-TriM and when I install in Jeti studio there's an error.
Error in DFM-TriM: ./Apps/DFM-TriM.lua:238: attempt to call a nil value
Can you please help me?

Thanks,
Pavel

**Comment by davidmcq137** [comment]
We are actively working on a released version, please stand by.
