### ISSUE TITLE
DFM-Maps: activate / deactivate noflightzone with a switch

### ISSUE THREAD

**Issue by jraichle** [davidmcq137/JetiLuaDFM#8]
Is it possible to make the noflightzone in the DFM-Maps switchable (activate / deactivate with a switch)? Background: on approach there is a row of trees which must first be overflown before the descent can begin. In the landing approach a warning would be very valuable here, but in the normal overflight it should be possible to switch of this warning

Best regards
Jochen

**Comment by davidmcq137** [comment]
i

**Comment by davidmcq137** [comment]
closed
